export default {
    mapHome: '',
    resultCount: 250,
    showLogo: false,
    relevancePrecision: 5,
    attributeDescriptions: {},
    basicSearchTemporalSelectionDefault: [
        'created',
        'effective',
        'modified',
        'metacard.created',
        'metacard.modified',
    ],
    branding: 'DDF',
    basicSearchMatchType: 'datatype',
    onlineGazetteer: true,
    imageryProviders: [
        {
            type: 'SI',
            url: './images/natural_earth_50m.png',
            parameters: {
                imageSize: [10800, 5400],
            },
            alpha: 1,
            name: 'Default Layer',
            show: true,
            proxyEnabled: true,
            order: 0,
        },
    ],
    isCacheDisabled: false,
    isVersioningEnabled: true,
    summaryShow: ['created', 'modified', 'thumbnail'],
    readOnly: [
        '^checksum$',
        '^checksum-algorithm$',
        '^id$',
        '^resource-download-url$',
        '^resource-uri$',
        '^resource.derived-uri$',
        '^resource.derived-download-url$',
        '^modified$',
        '^metacard-tags$',
        '^metacard-type$',
        '^metadata$',
        '^source-id$',
        '^point-of-contact$',
        '^metacard.',
        '^version.',
        '^validation.',
    ],
    version: '2.14.0-SNAPSHOT',
    i18n: {
        'sources.unavailable': '{amountDown} {amountDown, plural, one {source is} other {sources are}} currently down',
        'sources.polling.error.title': 'Error Polling Sources',
        'search.sources.selected.none.message': 'No sources are currently selected. Edit the search and select at least one source.',
        'sources.available': 'All sources are currently up',
        'sources.title': 'Sources',
        'sources.polling.error.message': 'Unable to query server for list of active sources',
        'sources.options.all': 'All Sources',
        'form.title': 'title',
    },
    isExperimental: false,
    resultPageSize: 25,
    sourcePollInterval: 60000,
    requiredAttributes: [],
    scheduleFrequencyList: [1800, 3600, 7200, 14400, 28800, 57600, 86400],
    facetWhitelist: [],
    terrainProvider: {
        type: 'CT',
        url: './proxy/catalog0',
    },
    hiddenAttributes: ['^sorts$', '^cql$', '^polling$', '^cached$'],
    timeout: 300000,
    attributeAliases: {},
    commonAttributes: [],
    enums: {},
    extra: {},
    editorAttributes: [],
    resultShow: [],
    disableUnknownErrorBox: false,
    theme: 'dark',
    projection: 'EPSG:4326',
    defaultLayout: [
        {
            type: 'stack',
            content: [
                {
                    type: 'component',
                    component: 'cesium',
                    componentName: 'cesium',
                    title: '3D Map',
                },
                {
                    type: 'component',
                    component: 'inspector',
                    componentName: 'inspector',
                    title: 'Inspector',
                },
            ],
        },
    ],
    webSocketsEnabled: false,
    showRelevanceScores: false,
    product: 'Intrigue',
    typeNameMapping: {},
    gazetteer: true,
    exportResultLimit: 1000,
    bingKey: '',
    useHyphensInUuid: false,
    disableLocalCatalog: false,
};
//# sourceMappingURL=config.js.map