name: Build distribution for downstream consumption
working-directory: ${{ github.workspace }}
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    working-directory: ui-frontend/packages/catalog-ui-search
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn run publish:build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: dist
