name: dist
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: "ddf-ui"

      - name: Install dependencies
        run: yarn install
        working-directory: ./ddf-ui/ui-frontend/packages/catalog-ui-search

      - name: Build project
        run: yarn run publish:build
        working-directory: ./ddf-ui/ui-frontend/packages/catalog-ui-search

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        working-directory: ./ddf-ui/ui-frontend/packages/catalog-ui-search
        with:
          name: my-artifact
          path: dist
