name: dist
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Change directory
        run: cd ui-frontend/packages/catalog-ui-search

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn run publish:build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: ui-frontend/packages/catalog-ui-search/dist
