name: publish-package

on:
  pull_request:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: "ddf-ui"

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: |
          cd ./ddf-ui/ui-frontend/packages/catalog-ui-search
          yarn install

      - name: Build project
        run: |
          cd ./ddf-ui/ui-frontend/packages/catalog-ui-search
          yarn run build

      - name: Set branch name
        id: set_branch_name
        run: echo ::set-output name=branch_name::catalog-ui-search-dist-${{ github.event.pull_request.number }}

      - name: Create temporary directory
        run: |
          mkdir -p ./dist

      - name: Copy dist directory to temporary directory
        run: |
          cp -R ./ddf-ui/ui-frontend/packages/catalog-ui-search/dist/. ./dist/

      - name: Remove original contents
        run: |
          rm -rf ./ddf-ui/*

      - name: Copy contents of temporary directory to ./ddf-ui
        run: |
          cp -R ./dist/. ./ddf-ui/

      - name: Commit and push changes
        run: |
          cd ./ddf-ui
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update catalog-ui-search package for PR #${{ github.event.pull_request.number }}"
          git push origin ${{ steps.set_branch_name.outputs.branch_name }} --force
